/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplicacion;
import modelo.IntervaloException;
import java.util.InputMismatchException;

/**
 *
 * @author zohan
 */
public class CalculadoraAplicacion extends javax.swing.JFrame {

    private String cadenaNumeros;
    private String operacion = "nada";
    private double primerTermino;
    private double resultado;
    private boolean activado = true;
    private boolean punto = true;
    private boolean continuar = true;
    
    
    public CalculadoraAplicacion() {
        initComponents();
        
        this.setTitle("calculadora");
        this.setLocationRelativeTo(null);
    }

    public static double cociente(double numerador, double denominador)
    throws ArithmeticException 
    {
        return numerador/denominador; //Punto de lanzamiento de una Excepción
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        btmClean = new javax.swing.JButton();
        btnMasMenos = new javax.swing.JButton();
        btnRaizCuadrada = new javax.swing.JButton();
        btnCe = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        lbNumeros = new javax.swing.JLabel();
        lbMostrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setToolTipText("");
        Panel.setLayout(new java.awt.GridLayout(5, 4));

        btmClean.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btmClean.setText("C");
        btmClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCleanActionPerformed(evt);
            }
        });
        Panel.add(btmClean);

        btnMasMenos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMasMenos.setText("+/-");
        btnMasMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasMenosActionPerformed(evt);
            }
        });
        Panel.add(btnMasMenos);

        btnRaizCuadrada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRaizCuadrada.setText("√");
        btnRaizCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizCuadradaActionPerformed(evt);
            }
        });
        Panel.add(btnRaizCuadrada);

        btnCe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCe.setText("CE");
        btnCe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeActionPerformed(evt);
            }
        });
        Panel.add(btnCe);

        btn9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        Panel.add(btn9);

        btn8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        Panel.add(btn8);

        btn7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        Panel.add(btn7);

        btnDividir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDividir.setText("/");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        Panel.add(btnDividir);

        btn6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        Panel.add(btn6);

        btn5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        Panel.add(btn5);

        btn4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        Panel.add(btn4);

        btnMultiplicar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMultiplicar.setText("x");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        Panel.add(btnMultiplicar);

        btn3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        Panel.add(btn3);

        btn2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        Panel.add(btn2);

        btn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        Panel.add(btn1);

        btnResta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        Panel.add(btnResta);

        btnPunto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        Panel.add(btnPunto);

        btn0.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        Panel.add(btn0);

        btnIgual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        Panel.add(btnIgual);

        btnSuma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        Panel.add(btnSuma);

        lbNumeros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNumeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNumeros.setText("0");
        lbNumeros.setToolTipText("");

        lbMostrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMostrar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMostrar.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        if (lbNumeros.getText().equals("0")){
            cadenaNumeros = "0";
        } else {
            cadenaNumeros += "0";
        }
        lbNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (lbNumeros.getText().equals("0")){
            cadenaNumeros = "1";
        } else {
            cadenaNumeros += "1";
        }
        lbNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (lbNumeros.getText().equals("0")){
            cadenaNumeros = "2";
        } else {
            cadenaNumeros += "2";
        }
        lbNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if (lbNumeros.getText().equals("0")){
            cadenaNumeros = "3";
        } else {
            cadenaNumeros += "3";
        }
        lbNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if (lbNumeros.getText().equals("0")){
            cadenaNumeros = "4";
        } else {
            cadenaNumeros += "4";
        }
        lbNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if (lbNumeros.getText().equals("0")){
            cadenaNumeros = "5";
        } else {
            cadenaNumeros += "5";
        }
        lbNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if (lbNumeros.getText().equals("0")){
            cadenaNumeros = "6";
        } else {
            cadenaNumeros += "6";
        }
        lbNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if (lbNumeros.getText().equals("0")){
            cadenaNumeros = "7";
        } else {
            cadenaNumeros += "7";
        }
        lbNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if (lbNumeros.getText().equals("0")){
            cadenaNumeros = "8";
        } else {
            cadenaNumeros += "8";
        }
        lbNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if (lbNumeros.getText().equals("0")){
            cadenaNumeros = "9";
        } else {
            cadenaNumeros += "9";
        }
        lbNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        if (activado==true){
            primerTermino = Double.parseDouble(cadenaNumeros);
            lbMostrar.setText(cadenaNumeros + " + ");
            cadenaNumeros = "";
            operacion = "suma";
            
            activado = false;
            
        }
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        double segundoTermino;
        if (operacion.equals("nada")){
            
            lbNumeros.setText(cadenaNumeros);
            
        } else if (operacion.equals("suma")){
            
            segundoTermino = Double.parseDouble(cadenaNumeros);
            resultado = primerTermino + segundoTermino;
            lbNumeros.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nada";
            
        } else if (operacion.equals("resta")){
            
            segundoTermino = Double.parseDouble(cadenaNumeros);
            resultado = primerTermino - segundoTermino;
            lbNumeros.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nada";
            
        } else if (operacion.equals("multiplicacion")){
            
            segundoTermino = Double.parseDouble(cadenaNumeros);
            resultado = primerTermino * segundoTermino;
            lbNumeros.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nada";
            
        } else if (operacion.equals("division")){
        do{
            try{
            segundoTermino = Double.parseDouble(cadenaNumeros);
            cociente(primerTermino,segundoTermino);
            resultado = primerTermino / segundoTermino;
            lbNumeros.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nada";
 
            if(segundoTermino == 0){
                    throw new IntervaloException("El denominador no puede ser cero");
                }
            continuar = false;
            }
             catch(ArithmeticException e1){               
                 lbMostrar.setText("el denominador no puede ser ");
                 StackTraceElement[] listaErrores = e1.getStackTrace();
                      for(int i=0; i < listaErrores.length; i++){
                     String mensaje = listaErrores[i].getClassName()+ ", " + listaErrores[i].getFileName() + ", " + listaErrores[i].getMethodName() + ", " + listaErrores[i].getLineNumber();
                 }
             }
        
        }while(continuar);
        }

        lbMostrar.setText("");
        activado = true;
        punto = false;
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
         if (activado==true){
            primerTermino = Double.parseDouble(cadenaNumeros);
            lbMostrar.setText(cadenaNumeros + " - ");
            cadenaNumeros = "";
            operacion = "resta";
            
            activado = false;
            
        }
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
         if (activado==true){
            primerTermino = Double.parseDouble(cadenaNumeros);
            lbMostrar.setText(cadenaNumeros + " x ");
            cadenaNumeros = "";
            operacion = "multiplicacion";
            
            activado = false;
            
        }
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
            if (activado==true){
            primerTermino = Double.parseDouble(cadenaNumeros);
            lbMostrar.setText(cadenaNumeros + " / ");
            cadenaNumeros = "";
            operacion = "division";
            
            activado = false;
            
        }
    }//GEN-LAST:event_btnDividirActionPerformed
  
    private void btnRaizCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizCuadradaActionPerformed
        primerTermino = Double.parseDouble(cadenaNumeros);
        lbMostrar.setText("srqt("+cadenaNumeros+")");
        resultado = Math.sqrt(primerTermino);
        lbNumeros.setText(String.format("% .2f", resultado));
        cadenaNumeros =String.valueOf(resultado);
        punto = false;
        
    }//GEN-LAST:event_btnRaizCuadradaActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        if (punto == true){
            if (cadenaNumeros.equals("")){
                cadenaNumeros = "0.";
            } else {
                cadenaNumeros += ".";
                
            }
            lbNumeros.setText(cadenaNumeros);
            punto = false;
            
        }
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnMasMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasMenosActionPerformed
        if (cadenaNumeros.charAt(0) != - '-'){
            cadenaNumeros = "-" + cadenaNumeros;
        } else {
            cadenaNumeros = cadenaNumeros.substring(1, cadenaNumeros.length());
        }
        lbNumeros.setText(cadenaNumeros);
    }//GEN-LAST:event_btnMasMenosActionPerformed

    private void btnCeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeActionPerformed
        int longitud = cadenaNumeros.length();
        if(longitud > 0){
            if (longitud == 1){
                cadenaNumeros = "0";
            } else {
                cadenaNumeros = cadenaNumeros.substring(0,cadenaNumeros.length() - 1);
            }
            lbNumeros.setText(cadenaNumeros);
        } 
    }//GEN-LAST:event_btnCeActionPerformed

    private void btmCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCleanActionPerformed
        lbNumeros.setText("");
        lbMostrar.setText("");
        operacion = "nada";
        cadenaNumeros = "";
        punto = true;
        activado = true;
    }//GEN-LAST:event_btmCleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraAplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btmClean;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnCe;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMasMenos;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRaizCuadrada;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel lbMostrar;
    private javax.swing.JLabel lbNumeros;
    // End of variables declaration//GEN-END:variables
}
